### PR TITLE
Appimage

### PR DESCRIPTION
**Pull request by Restioson**
This adds AppImages for Vertex Linux distribution - an install-less, cross-distro application format.

### CODE REVIEW

**Comment by Restioson** [comment]
Looks like I still need to include some libraries here. At least GTK and openAL I think. Also, AppImages don't appear to run on non-glibc systems.

**Comment by Restioson** [comment]
Closed in favour of #35 (Flatpak)

**Comment by probonopd** [comment]
Hi, interesting project. Definitely worthwhile.

Please do provide an AppImage for those who cannot or do not want to run Flatpak (e.g., Live system users like myself).

Can I help with anything AppImage related?

Maybe you'd like to check out my new experimental appimagetool:
https://github.com/probonopd/go-appimage/tree/master/src/appimagetool

**Comment by Restioson** [comment]
Hi, thanks for the comment! 

I don't exactly remember what the exact issue was but I think it was something to do with bundling libraries. I'm not exactly sure what the libraries are and how to bundle them properly so that they work on all versions of Linux. In the end I went with flatpak since that was just the solution that ended up working, but I am not opposed to appimage in the future and it does have some notable advantages (e.g not having to download new runtimes for one application). I am relatively new to deploying software.

I will check out that tool, thank you! Is there documentation for how to use it anywhere?

**Comment by probonopd** [comment]
Hi @Restioson thanks for you reply. Here is the documentation: https://github.com/probonopd/go-appimage/blob/master/src/appimagetool/README.md - feel free to reach out if something is not working as expected.

**Pull request closed without merging**
