### PR TITLE
Accessibility

### LINKED ISSUE #37: Accessibility
Vertex's client should be accessible to people who are visually impaired. Currently it should work for people who are deaf or have other hearing impairments, because notifications also are pushed at a system level. ATK is the toolkit for doing this with GTK, though we might want to move away from GTK at some point. https://docs.rs/atk/0.8.0/atk/

### PR DESCRIPTION
**Pull request by Restioson**
This should make the Vertex client more accessible to blind people. Fixes #37.

Input from @devinprater: https://anarchism.space/@restioson/104007947210024172

Work done:
- [x] Convert button mouse press events to clicked events
- [x] Add flavour text back to errors (I like it - [image](https://user-images.githubusercontent.com/6688948/80199525-ba8bfa80-8621-11ea-9602-c562cebeb041.png))
- [x] Open server settings popover
- [x] Investigate how dialogs work with a11y (we use mouse effects to dismiss them currently)
- [x] Fix settings
- [x] Announce new messages
- [x] Accessibility mode in settings

### CODE REVIEW

**Comment by Restioson** [comment]
Dialogs don't get announced when opened, which is an issue. Will need to find a way to do that. Also, we need to add a close button to them and maybe escape as a shortcut.

**Comment by Restioson** [comment]
Fixed dialogs now by converting them to gtk::Dialogs proper.

**Comment by Restioson** [comment]
For announcing new messages, we could send system notifications or find some way to notify atk.

EDIT: implemented.

**Comment by Restioson** [comment]
For accessible scrolling up, we can check when the topmost message is selected and then load more.

**Review by Gegy — APPROVED** [review]

**Pull request merged**
