### PR TITLE
Native client

### PR DESCRIPTION
**Pull request by Restioson**
@gegy1000 thoughts? This does away with electron.

### CODE REVIEW

**Comment by gegy1000** [comment]
This looks great! Not too familiar with the codebase, so can't really comment on that regard.

One thought: should we keep backend separate in `client` still (now that they are the same language)? Might be fine to merge, but idk.

**Comment by Restioson** [comment]
You raised a possibility of an android client, so I separated them.

**Comment by gegy1000** [comment]
Oh, right! Good point. What's the current policy on when something should go in `gtk/` or `backend/`?

**Comment by Restioson** [comment]
`gtk`: GUI frontend stuff.
`backend`: handling messages from server. The `Vertex::handle` method returns `Action` which indicates what the GUI frontend should do.

**Pull request merged**
